"""empty message

Revision ID: 717652216e99
Revises: 
Create Date: 2023-03-11 23:05:32.562307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '717652216e99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_image', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=10485759),
               existing_nullable=False)

    with op.batch_alter_table('product_base', schema=None) as batch_op:
        batch_op.drop_column('shoe_type')
        batch_op.drop_column('shoe_height')
        batch_op.drop_column('colors')
        batch_op.drop_column('shoe_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shoe_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('colors', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('shoe_height', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('shoe_type', mysql.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('category_image', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(length=10485759),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
